### ISSUE TITLE
Login via ORCID impossible

### ISSUE THREAD

**Issue by LasKru** [molbiodiv/bcdatabaser_web#18]
When trying to login with ORCID, i get redirected to ORCID and i can login, but after pressing "authorize access", i get a "Authentication failed" error.  This has been the case for at least a couple of weeks already. I'm not sure if this is a bcdatabaser or a ORCID problem.

**Comment by iimog** [comment]
Thanks for reporting this issue! For some reason the server was unable to resolve some DNS names. I restarted the resolver there and now it works again. Please confirm it is working and feel free to report immediately if this issue re-appears. I'll try to setup some monitoring as well.

**Comment by LasKru** [comment]
It seems to work now! That was a quick solution, thank you very much!
