### ISSUE TITLE
Setting parameters for pipeline

### ISSUE THREAD

**Issue by sonjahohlfeld** [molbiodiv/bcdatabaser_web#2]
The following parameters can be set via the web interface:
- [ ] search string (dropdown for frequent patterns, custom option as advanced feature)
- [ ] taxonomic range (scientific name, NCBI taxonomy)
- [ ] taxa list (upload text file)
- [ ] sequence length filter

It should be possible to set advanced parameters. These are initially hidden.
- [ ] custom pattern as search string
- [ ] HMM files
- [ ] Primer files

**Comment by iimog** [comment]
Only a limited set of options is available to the user. For more detailed settings users have to download and use the command line version
